CREATE FUNCTION "EXP_GetRutasPRE"
(  
	in ItemCode NVARCHAR(50)
)  
returns TABLE 
(
	"RUTA" int,
	"PRED" varchar(5000)

)
LANGUAGE SQLSCRIPT AS 
BEGIN  
	
RETURN 
SELECT  "RUTA", STRING_AGG("PRED",',') "PRED" FROM(SELECT DISTINCT  *FROM(
	select 'EXT' "TIPO", EXT."U_EXP_CDRTDE" "RUTA",  FRU."LineId" "PRED"
	FROM OITM "ITM" 
    JOIN "@EXP_OFRM" "FO0" ON ITM."U_EXP_FORM"=FO0."Code" 
	JOIN "@EXP_FFRUTA" "FRU" ON FO0."Code"=FRU."Code" 
	JOIN "@EXP_FREXTR" "EXT" ON  FO0."Code"=EXT."Code" AND FRU."LineId"=EXT."U_EXP_CODRUTDE"
	WHERE  ITM."ItemCode"=:ItemCode AND FRU."U_EXP_CODRUT" IN ('EXT') 
	UNION ALL
	select DISTINCT FRU."U_EXP_CODRUT" "TIPO", FRU."LineId" "RUTA", 0 "PRED"
	FROM OITM "ITM" 
    JOIN "@EXP_OFRM" "FO0" ON ITM."U_EXP_FORM"=FO0."Code" 
	JOIN "@EXP_FFRUTA" "FRU" ON FO0."Code"=FRU."Code" 
	JOIN "@EXP_FREXTR" "EXT" ON  FO0."Code"=EXT."Code" AND FRU."LineId"=EXT."U_EXP_CODRUTDE" 				
	WHERE  ITM."ItemCode"=:ItemCode
	UNION ALL
	select DISTINCT FRU."U_EXP_CODRUT" "TIPO", FRU."LineId" "RUTA", IFNULL(IMP."U_EXP_CODRUTOR",0) "PRED"
	FROM OITM "ITM" 
    JOIN "@EXP_OFRM" "FO0" ON ITM."U_EXP_FORM"=FO0."Code" 
	JOIN "@EXP_FFRUTA" "FRU" ON FO0."Code"=FRU."Code" 
	JOIN "@EXP_FRIMPR" "IMP" ON  FO0."Code"=IMP."Code" AND FRU."LineId"=IMP."U_EXP_CODRUT" 					
	WHERE  ITM."ItemCode"=:ItemCode
UNION ALL
	select DISTINCT FRU."U_EXP_CODRUT" "TIPO", FRU."LineId" "RUTA",  IFNULL(LAM."U_EXP_CODRUTOR",0) "PRED"
	FROM OITM "ITM" 
    JOIN "@EXP_OFRM" "FO0" ON ITM."U_EXP_FORM"=FO0."Code" 
	JOIN "@EXP_FFRUTA" "FRU" ON FO0."Code"=FRU."Code" 
	JOIN "@EXP_LAMINA" "LAM" ON  FO0."Code"=LAM."Code" AND FRU."LineId"=LAM."U_EXP_CODRUT" 					
	WHERE  ITM."ItemCode"=:ItemCode	
UNION ALL
	select DISTINCT FRU."U_EXP_CODRUT" "TIPO", FRU."LineId" "RUTA",  IFNULL(SEL."U_EXP_CODRUTOR",0) "PRED"
	FROM OITM "ITM" 
    JOIN "@EXP_OFRM" "FO0" ON ITM."U_EXP_FORM"=FO0."Code" 
	JOIN "@EXP_FFRUTA" "FRU" ON FO0."Code"=FRU."Code" 
	JOIN "@EXP_FRSELA" "SEL" ON  FO0."Code"=SEL."Code" AND FRU."LineId"=SEL."U_EXP_CODRUT" 						
	WHERE  ITM."ItemCode"=:ItemCode		
UNION ALL
	select DISTINCT FRU."U_EXP_CODRUT" "TIPO", FRU."LineId" "RUTA",  IFNULL(COR."U_EXP_CODRUTOR",0) "PRED"
	FROM OITM "ITM" 
    JOIN "@EXP_OFRM" "FO0" ON ITM."U_EXP_FORM"=FO0."Code" 
	JOIN "@EXP_FFRUTA" "FRU" ON FO0."Code"=FRU."Code" 
	 JOIN "@EXP_FRCORT" "COR" ON  FO0."Code"=COR."Code" AND FRU."LineId"=COR."U_EXP_CODRUT" 					
	WHERE  ITM."ItemCode"=:ItemCode		
UNION ALL
	select DISTINCT FRU."U_EXP_CODRUT" "TIPO", FRU."LineId" "RUTA",  IFNULL(HAB."U_EXP_CODRUTOR",0) "PRED"
	FROM OITM "ITM" 
    JOIN "@EXP_OFRM" "FO0" ON ITM."U_EXP_FORM"=FO0."Code" 
	JOIN "@EXP_FFRUTA" "FRU" ON FO0."Code"=FRU."Code" 
	JOIN "@EXP_FRHABI" "HAB" ON  FO0."Code"=HAB."Code" AND FRU."LineId"=HAB."U_EXP_CODRUT" 				
	WHERE  ITM."ItemCode"=:ItemCode		
UNION ALL
	select DISTINCT FRU."U_EXP_CODRUT" "TIPO", FRU."LineId" "RUTA",  IFNULL(REB."U_EXP_CODRUTOR",0) "PRED"
	FROM OITM "ITM" 
    JOIN "@EXP_OFRM" "FO0" ON ITM."U_EXP_FORM"=FO0."Code" 
	JOIN "@EXP_FFRUTA" "FRU" ON FO0."Code"=FRU."Code" 
	JOIN "@EXP_FRREBO" "REB" ON  FO0."Code"=REB."Code" AND FRU."LineId"=REB."U_EXP_CODRUT" 					
	WHERE  ITM."ItemCode"=:ItemCode		
UNION ALL
	select DISTINCT FRU."U_EXP_CODRUT" "TIPO", FRU."LineId" "RUTA",  IFNULL(SER."U_EXP_CODRUTOR",0) "PRED"
	FROM OITM "ITM" 
    JOIN "@EXP_OFRM" "FO0" ON ITM."U_EXP_FORM"=FO0."Code" 
	JOIN "@EXP_FFRUTA" "FRU" ON FO0."Code"=FRU."Code" 
	JOIN "@EXP_FRSERV" "SER" ON  FO0."Code"=SER."Code" AND FRU."LineId"=SER."U_EXP_CODRUT" 					
	WHERE  ITM."ItemCode"=:ItemCode				
)) GROUP BY "RUTA" order by "RUTA" ;
  
end;


